''' Protocol info '''
HEADER_SIZE = 16
PORT = 5050
ENCODING_FORMAT = 'utf-8'

SERVER_ADDR = '192.168.1.127'

''' Message info '''
TYPE_SEPARATOR = ':'
INTRA_SEPARATOR = ','
ADD_ENTRY_MESSAGE = 'ADD ENTRY'
SEND_TEXT_MESSAGE = 'SEND MESSAGE'
DISCONNECT_MESSAGE = 'DISCONNECT'
QUERY_MESSAGE = 'QUERY'
